Public Enum InternationalSettings
    None
    Locale
    LocaleName
    s1159
    s2359
    sCountry
    sCurrency
    sDate
    sDecimal
    sGrouping
    sLanguage
    sList
    sLongDate
    sMonDecimalSep
    sMonGrouping
    sMonThousandSep
    sNativeDigits
    sNegativeSign
    sPositiveSign
    sShortDate
    sThousand
    sTime
    sTimeFormat
    sShortTime
    sYearMonth
    iCalendarType
    iCountry
    iCurrDigits
    iCurrency
    iDate
    iDigits
    NumShape
    iFirstDayOfWeek
    iFirstWeekOfYear
    iLZero
    iMeasure
    iNegCurr
    iNegNumber
    iPaperSize
    iTime
    iTimePrefix
    iTLZero
End Enum